In [1]:
import numpy as np

N = 1_000_000

my_arr = np.arange(N)
my_list = list(range(N))

In [2]:
%timeit my_arr2 = my_arr * 2

250 μs ± 989 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
%timeit my_list2 = [x * 2 for x in my_list]

13.1 ms ± 132 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]]); data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10; data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [9]:
data.ndim, data.shape, data.dtype

(2, (2, 3), dtype('float64'))

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,3,2)) # use only if you intent to populate it with data

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64); arr1

array([1., 2., 3.])

In [15]:
arr2 = np.array([1, 2, 3], dtype=np.int32); arr2

array([1, 2, 3], dtype=int32)

In [2]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64); float_arr

array([1., 2., 3., 4., 5.])

In [3]:
numeric_strings = np.array(["1.25", "-9.6", "42"])

numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])